### ISSUE TITLE
ValueError: The number of observations cannot be determined on an empty distance matrix.

### ISSUE THREAD

**Issue by sunettevos** [rotheconrad/mHEAT-binder#1]
Good day

I am trying to use this tool to see the completeness of my pathways. I have a file, which according to my eye looks like the same format as the input example file. However, by using the following command I get the following error. 

The command:
!KEGG-decoder --input Accession-numbers-with-site-1-sediment.txt --output test_output_data.tsv --vizoption interactive

The error:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/KEGG-decoder", line 8, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/KEGGDecoder/KEGG_decoder.py", line 1379, in main
    plotly_viz(genome)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/KEGGDecoder/Plotly_viz.py", line 12, in plotly_viz
    Euclidean_genome_df = hClust_euclidean(genome_df)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/KEGGDecoder/KEGG_clustering.py", line 10, in hClust_euclidean
    linkage_matrix = linkage(genome_df, method='average', metric='euclidean')
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 1064, in linkage
    n = int(distance.num_obs_y(y))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2403, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.

Last time, I changed the interactive part in the command to static, this was working last time, suddenly it is not working anymore. Any ideas and thoughts on this error will be highly appreciated. I have attached the input file I am using. Any help on this will be appreciated, thank you.

Regards
Sunette
[Accession-numbers-with-site-1-sediment.txt](https://github.com/rotheconrad/KEGGDecoder-binder/files/4872332/Accession-numbers-with-site-1-sediment.txt)

**Comment by bjtully** [comment]
Hi Sunette,

Because of the way this version interactive visualization works, it cannot accept a single genome entry. The current version of KEGG-Decoder (available here: https://github.com/bjtully/BioData) will accept 2 genomes as the minimum number with the interactive visualization output.

Cheers
Ben
